name: Build and Publish image to dockerhub
on:
  push:
    branch:
      - dev

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build . -t monta55ir/docker-api:latest
      - name: push image to docker hub
        run: |
          docker push monta55ir/docker-api:latest
